### ISSUE TITLE
no-deprecated rule makes eslint to fail with an exception

### ISSUE THREAD

**Issue by adrm** [cartant/eslint-plugin-etc#34]
When I run eslint, I get this error:

```sh
Oops! Something went wrong! :(

ESLint: 7.31.0

TypeError: tag.trim is not a function
```

The stack trace goes like this (personal info censored):

```
Occurred while linting ***
    at Identifier (***/node_modules/eslint-plugin-etc/dist/rules/no-deprecated.js:86:46)
    at ***/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (***/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (***/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (***/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (***/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (***/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at ***/node_modules/eslint/lib/linter/linter.js:960:32
    at Array.forEach (<anonymous>)
```

When I disable this rule, the analysis ends as expected.

**Comment by cartant** [comment]
What package version are you using? And what are the TypeScript and ESLint TypeScript parser versions?

**Comment by adrm** [comment]
Sorry for not giving this info upfront.

```
typescript@4.3.5
@typescript-eslint/parser@4.28.5
```

Thanks!

**Comment by cartant** [comment]
To take this further, you'd need to provide a minimal reproduction, as I'm unable to reproduce the problem with the tests in this project or with several of the projects in which I've used the rule. And I cannot see how something other than an array of strings could be returned from [here](https://github.com/cartant/eslint-plugin-etc/blob/7a0552e3867cfbc958ca2fff25a82ee5b9e24d47/source/tslint-tag.ts#L128-L142) or [here](https://github.com/cartant/eslint-plugin-etc/blob/7a0552e3867cfbc958ca2fff25a82ee5b9e24d47/source/tslint-tag.ts#L197-L219).

**Comment by adrm** [comment]
Thanks for checking it. We'll try to make a minimal reproduction as soon as possible.
